### ISSUE TITLE
BadBoy is not working after changed NewUI

### ISSUE THREAD

**Issue by guiguziking** [BadBoy-Ultimate-Raider/BadBoy#172]
Hi,Thank you for your work,I love the BadBoy. Since the NewUI changed, I found my BadBoy is not working now. Even I Can't see the any of the MinimapButton and main icon and UI. I'm sure  I have load BadBoy and the Firehack Inject Correct. I have delete role information in the WTF Folder.
My system is window's 7 at first and I upgraded to window's 10, But it's still not working.
While I replace the BadBoy by the old vision without NewUI, it working normal.

Besides, I'm in China. I have these fonts in my clients: ARHei.ttf, ARKai_C.ttf, ARKai_T.ttf

**Comment by Defmaster** [comment]
Hey, i added an extra check for loading. It seems some option are not always correctly saved first time. Report back up the commit fixed it for you.

**Comment by guiguziking** [comment]
Hi, Thanks for your prompt answer. I have tried the new badboy, The problem is still the same, It doesn't show any of the MinimapButton or main icon or UI. 
Very few times there are lua error like this:
Message: ...dBoy\System\Libs\DiesalStyle-1.0\DiesalStyle-1.0.lua:7: Cannot find a library instance of "LibSharedMedia-3.0".
Time: 11/04/15 08:20:13
Count: 1
Stack: [C]: in function `error'
Interface\AddOns\BadBoy\System\UsefulFeatures.lua:179: in function `LibStub'
...dBoy\System\Libs\DiesalStyle-1.0\DiesalStyle-1.0.lua:7: in main chunk
Locals: (*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."

But Most of the time there is no lua error window.

**Comment by Defmaster** [comment]
I pushed a new release.
LibSharedMedia was not set in TOC file. I never noticed because another addon loaded it :D
Hope this fix it.
Now i tested it with only BB active

**Comment by guiguziking** [comment]
I have tried again and still can't see any of the MinimapButton or main icon or UI. 
There are still a lot of 

Message: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: attempt to index field '?' (a nil value)
Time: 11/05/15 08:53:53
Count: 4366
Stack: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\LootManager.lua:165: in function <Interface\AddOns\BadBoy\System\LootManager.lua:164>

Locals: Value = "Auto Loot"
new = true
(*temporary) = nil
(*temporary) = "Auto LootCheck"
(*temporary) = "Check"
(*temporary) = "attempt to index field '?' (a nil value)"


Message: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:22
Count: 3
Stack: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:14: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:13>

Locals: Value = "Interrupts Handler"
new = true
(*temporary) = nil
(*temporary) = "Interrupts HandlerCheck"
(*temporary) = "Check"
(*temporary) = "attempt to index field '?' (a nil value)"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 11/05/15 08:36:51
Count: 154
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\LootManager.lua:165: in function <Interface\AddOns\BadBoy\System\LootManager.lua:164>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:36:08
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 11/05/15 08:44:22
Count: 3
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:14: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:13>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:13
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"



Message: Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 11/05/15 08:44:22
Count: 318
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:14: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:13>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:13
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: C stack overflow
Time: 11/05/15 08:36:51
Count: 154
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\LootManager.lua:165: in function <Interface\AddOns\BadBoy\System\LootManager.lua:164>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:36:08
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = "C stack overflow"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: C stack overflow
Time: 11/05/15 08:44:22
Count: 3
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\readers\combatlog.lua:11: in function `enrageReader'
Interface\AddOns\BadBoy\System\readers\combatlog.lua:79: in function `common'
Interface\AddOns\BadBoy\System\readers\combatlog.lua:48: in function <Interface\AddOns\BadBoy\System\readers\combatlog.lua:43>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:13
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = "C stack overflow"

**Comment by guiguziking** [comment]
Thank you very much.I have tried again and still can't see any of the MinimapButton or main icon or UI.
There are still a lot of lua errors.

Message: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: attempt to index field '?' (a nil value)
Time: 11/05/15 08:53:53
Count: 4366
Stack: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\LootManager.lua:165: in function <Interface\AddOns\BadBoy\System\LootManager.lua:164>

Locals: Value = "Auto Loot"
new = true
(*temporary) = nil
(*temporary) = "Auto LootCheck"
(*temporary) = "Check"
(*temporary) = "attempt to index field '?' (a nil value)"


Message: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:22
Count: 3
Stack: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:14: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:13>

Locals: Value = "Interrupts Handler"
new = true
(*temporary) = nil
(*temporary) = "Interrupts HandlerCheck"
(*temporary) = "Check"
(*temporary) = "attempt to index field '?' (a nil value)"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 11/05/15 08:36:51
Count: 154
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\LootManager.lua:165: in function <Interface\AddOns\BadBoy\System\LootManager.lua:164>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:36:08
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 11/05/15 08:44:22
Count: 3
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:14: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:13>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:13
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"



Message: Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 11/05/15 08:44:22
Count: 318
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:14: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:13>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:13
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: C stack overflow
Time: 11/05/15 08:36:51
Count: 154
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\LootManager.lua:165: in function <Interface\AddOns\BadBoy\System\LootManager.lua:164>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:36:08
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = "C stack overflow"


Message: Interface\FrameXML\UIPanelTemplates.lua:120: C stack overflow
Time: 11/05/15 08:44:22
Count: 3
Stack: Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\FrameXML\UIPanelTemplates.lua:120: in function `ScrollingEdit_OnUpdate'
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...
Interface\FrameXML\UIPanelTemplates.lua:97: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:22: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2233: in function <Interface\AddOns\BadBoy\System\GeneralFunctions.lua:2228>
(tail call): ?
Interface\AddOns\BadBoy\System\readers\combatlog.lua:11: in function `enrageReader'
Interface\AddOns\BadBoy\System\readers\combatlog.lua:79: in function `common'
Interface\AddOns\BadBoy\System\readers\combatlog.lua:48: in function <Interface\AddOns\BadBoy\System\readers\combatlog.lua:43>

Locals: self = ScriptErrorsFrameScrollFrameText {
 0 = <userdata>
 text = "Message: Interface\AddOns\BadBoy\BadBoy.lua:71: attempt to index field '?' (a nil value)
Time: 11/05/15 08:44:13
Count: 1
Stack: Interface\AddOns\BadBoy\BadBoy.lua:71: in function `Run'
Interface\AddOns\BadBoy\System\Core.lua:194: in function <Interface\AddOns\BadBoy\System\Core.lua:192>

Locals: self = <table> {
 PulseUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:274
 Engine = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:1
 DBM = <table> {
 }
 StartUI = <function> defined @Interface\AddOns\BadBoy\BadBoy.lua:265
 saveWindowPosition = <function> defined @Interface\AddOns\BadBoy\System\Core.lua:154
 dropOptions = <table> {
 }
 im = <unnamed> {
 }
 castOffensiveDispel = <function> defined @Interface\AddOns\BadBoy\System\engines\EnemiesEngineFunctions.lua:12
 AcceptQueues = <function> defined @Interface\AddOns\BadBoy\System\UsefulFeatures.lua:1
 checkProfileW handleCursorChange = true
}
elapsed = 0
scrollFrame = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
height = 193.99998474121
range = 0
scroll = 0
size = 193.99998474121
cursorOffset = nil
(*temporary) = nil
(*temporary) = ScriptErrorsFrameScrollFrame {
 ScrollBar = ScriptErrorsFrameScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Interface\FrameXML\UIPanelTemplates.lua:120: attempt to perform arithmetic on field 'cursorOffset' (a nil value)"
(*temporary) = "C stack overflow"

**Comment by Defmaster** [comment]
Love when errors appear I did not get yet. 
Will try to fix it when I am back home. 
A variable is used before it's set. 
Will make sure a default is set. To hopefully fix it.

**Comment by Defmaster** [comment]
Pushed somethin new.
Please try to use http://www.curse.com/addons/wow/addon-loader also. And report if it helped.

**Comment by guiguziking** [comment]
Hey, Thank you so much. Congratulations! The bugs have been terminated.
Badboy working normal now!
